# Site settings
title: Your awesome title
email: your-email@domain.com
description: "description goes here" 
twitter_username: jekyllrb
github_username:  jekyll
baseurl: "/freelancer-theme"

# Build settings
markdown: kramdown
permalink: pretty
