# Site settings
title: Eric & Kelsey
email: ericladler@gmail.com
description: "building a wedding website" 
twitter_username: jekyllrb
github_username:  jekyll
baseurl: "/eric-kelsey"

# Build settings
markdown: kramdown
permalink: pretty
