# Site settings
title: Eric & Kelsey
email: your-email@domain.com
description: "description goes here" 
twitter_username: jekyllrb
github_username:  jekyll
baseurl: "/eric-kelsey"

# Build settings
markdown: kramdown
permalink: pretty
